export const JEV_AUTOMATION_POLICY_VERSION = "2026-09-22.automation.v2";

export type JevAutomationSurface = "browser" | "computer";

export type JevAutomationValue = string | number | boolean | readonly string[] | null;

export type JevAutomationNavigationTarget =
  | { readonly kind: "url"; readonly url: string }
  | {
      readonly kind: "environment-port";
      readonly port: number;
      readonly protocol?: "http" | "https" | undefined;
      readonly path?: string | undefined;
    };

export interface JevAutomationElementReference {
  readonly documentId: string;
  readonly frameId: string;
  readonly elementId: string;
}

export interface JevAutomationDocumentFreshness {
  readonly documentId: string;
  readonly revision: string;
  readonly status: "current" | "changed" | "unknown";
}

export interface JevAutomationOption {
  readonly value: string;
  readonly label: string;
  readonly disabled?: boolean;
  readonly selected?: boolean;
}

export interface JevAutomationControl {
  /** Opaque, adapter-owned identifier. Never interpreted as a selector by the core. */
  readonly id: string;
  readonly reference?: JevAutomationElementReference;
  readonly role: string;
  readonly name?: string;
  readonly text?: string;
  readonly description?: string;
  readonly value?: JevAutomationValue;
  readonly checked?: boolean;
  readonly disabled?: boolean;
  readonly options?: readonly JevAutomationOption[];
}

export type JevAutomationOperation =
  | "activate"
  | "set-text"
  | "select-option"
  | "set-checked"
  | "hover"
  | "navigate"
  | "scroll"
  | "press-key";

export type JevAutomationInputKind = "text" | "url" | "navigation" | "option" | "scroll" | "key";

export type JevAutomationInput =
  | {
      readonly id: string;
      readonly kind: Exclude<JevAutomationInputKind, "navigation">;
      readonly value: string;
      readonly description: string;
    }
  | {
      readonly id: string;
      readonly kind: "navigation";
      readonly target: JevAutomationNavigationTarget;
      readonly description: string;
    };

/** A legal operation/target/input tuple generated by the host adapter. */
export interface JevAutomationCandidate {
  readonly id: string;
  readonly operation: JevAutomationOperation;
  readonly targetId?: string;
  readonly inputId?: string;
  readonly checked?: boolean;
  readonly description: string;
}

export interface JevAutomationObservation {
  /** Changes whenever an adapter's actionable state changes. */
  readonly revision: string;
  readonly document?: JevAutomationDocumentFreshness;
  readonly surface: JevAutomationSurface;
  readonly location?: string;
  readonly title?: string;
  readonly visibleText?: string;
  readonly omissions?: readonly string[];
  /** Safe adapter-derived values such as available options, scroll directions, or keys. */
  readonly inputs?: readonly JevAutomationInput[];
  readonly controls: readonly JevAutomationControl[];
  readonly candidates: readonly JevAutomationCandidate[];
}

export interface JevAutomationAction {
  readonly candidateId: string;
  readonly operation: JevAutomationOperation;
  readonly targetId?: string;
  readonly inputId?: string;
  /** Resolved only from a supplied input; never authored by the decision model. */
  readonly value?: string;
  /** Resolved only from a supplied logical navigation input. */
  readonly navigationTarget?: JevAutomationNavigationTarget;
  /** Desired state for set-checked; never inferred as a blind toggle. */
  readonly checked?: boolean;
}

export type JevAutomationExecutionResult =
  | { readonly status: "executed"; readonly detail?: string }
  | { readonly status: "stale"; readonly detail?: string }
  | { readonly status: "rejected"; readonly detail: string };

export interface JevAutomationAdapter {
  observe(input: { readonly signal: AbortSignal }): Promise<JevAutomationObservation>;
  /** Optional only for mixed-version adapters. Assertion-bearing runs fail closed without it. */
  verify?(input: {
    readonly assertions: readonly JevAutomationAssertion[];
    readonly expectedDocumentId?: string;
    readonly signal: AbortSignal;
  }): Promise<JevAutomationVerificationResult>;
  execute(input: {
    readonly revision: string;
    readonly action: JevAutomationAction;
    readonly signal: AbortSignal;
  }): Promise<JevAutomationExecutionResult>;
}

export type JevAutomationFrameSelector =
  | { readonly kind: "semantic"; readonly name: string }
  | { readonly kind: "locator"; readonly locator: string };

export type JevAutomationFrameScope =
  | { readonly kind: "main" }
  | { readonly kind: "frame-path"; readonly frames: readonly JevAutomationFrameSelector[] }
  | { readonly kind: "all-authorized-frames" };

export type JevAutomationAncestor =
  | {
      readonly kind: "semantic";
      readonly role: "dialog" | "region" | "form" | "group";
      readonly name: string;
    }
  | { readonly kind: "locator"; readonly locator: string };

export interface JevAutomationSemanticTarget {
  readonly role: string;
  readonly name: string;
  readonly scope?: {
    readonly frame?: JevAutomationFrameScope;
    readonly ancestor?: JevAutomationAncestor;
  };
}

export type JevAutomationControlTarget =
  | {
      /** Stable adapter id, when the caller obtained one from an earlier observation. */
      readonly targetId: string;
      readonly target?: never;
    }
  | {
      readonly targetId?: never;
      /** Pre-observation semantic target. Both fields match exactly and must be unique. */
      readonly target: JevAutomationSemanticTarget;
    };

export type JevAutomationAssertion =
  | {
      readonly kind: "location";
      readonly property: "location" | "title" | "visibleText";
      readonly operator: "equals" | "contains";
      readonly expected: string;
    }
  | ({ readonly kind: "control-exists" } & JevAutomationControlTarget)
  | ({
      readonly kind: "control";
      readonly property: "value" | "disabled" | "checked" | "name" | "text" | "selectedLabel";
      readonly operator: "equals" | "contains";
      readonly expected: JevAutomationValue;
    } & JevAutomationControlTarget)
  | {
      readonly kind: "control-count";
      readonly target: JevAutomationSemanticTarget;
      readonly operator: "equals" | "at-least" | "at-most";
      readonly expected: number;
    };

export type JevAutomationVerificationVerdict = "passed" | "failed" | "indeterminate";

export interface JevAutomationVerificationCoverage {
  readonly status: "complete" | "partial" | "unsupported";
  readonly searchedScopes: number;
  readonly omittedScopes: number;
  readonly omissions: readonly string[];
}

export interface JevAutomationAssertionResult {
  readonly assertion: JevAutomationAssertion;
  readonly passed: boolean;
  readonly verdict?: JevAutomationVerificationVerdict;
  readonly actual?: JevAutomationValue;
  readonly reason?: string;
  readonly matchCount?: number;
  readonly coverage?: JevAutomationVerificationCoverage;
  readonly document?: JevAutomationDocumentFreshness;
}

export interface JevAutomationVerificationAssertionResult extends JevAutomationAssertionResult {
  readonly verdict: JevAutomationVerificationVerdict;
  readonly matchCount: number;
  readonly coverage: JevAutomationVerificationCoverage;
  readonly document: JevAutomationDocumentFreshness;
  readonly matches?: readonly JevAutomationElementReference[];
}

export interface JevAutomationVerificationResult {
  readonly results: readonly JevAutomationVerificationAssertionResult[];
}

export interface JevAutomationAccounting {
  readonly inputTokens: number | null;
  readonly outputTokens: number | null;
  readonly costUsd: number | null;
  readonly responseModel?: string;
  readonly provider?: string;
}

export type JevAutomationNeedsAgentReason =
  | "novel-text"
  | "visual-understanding"
  | "unsupported-operation"
  | "ambiguous-state";

export type JevAutomationDecision =
  | {
      readonly outcome: "act";
      readonly candidateId: string;
    }
  | { readonly outcome: "done" }
  | { readonly outcome: "needs-agent"; readonly reason: JevAutomationNeedsAgentReason }
  | { readonly outcome: "unavailable"; readonly reason: string };

export interface JevAutomationDecisionResult {
  readonly decision: JevAutomationDecision;
  readonly accounting: JevAutomationAccounting;
}

export interface JevAutomationDecisionClient {
  decide(input: {
    readonly task: string;
    readonly observation: JevAutomationObservation;
    readonly inputs: readonly JevAutomationInput[];
    readonly unmetConditions: readonly JevAutomationAssertionResult[];
    readonly priorReceipts: readonly JevAutomationReceipt[];
    readonly signal: AbortSignal;
  }): Promise<JevAutomationDecisionResult>;
}

export interface JevAutomationReceipt {
  readonly iteration: number;
  readonly revision: string;
  readonly decision: JevAutomationDecision;
  readonly accounting: JevAutomationAccounting;
  readonly candidateId?: string;
  readonly status: "proposed" | "executed" | "rejected" | "stale" | "needs-agent" | "unavailable";
  readonly detail?: string;
}

export interface JevAutomationRequest {
  readonly task: string;
  readonly inputs?: readonly JevAutomationInput[];
  readonly assertions?: readonly JevAutomationAssertion[];
  readonly limits?: {
    readonly maxSteps?: number;
    readonly maxDecisionCalls?: number;
    readonly maxCostUsd?: number;
  };
  readonly signal?: AbortSignal;
  /** Called in order; an accepted proposal is emitted before adapter execution. */
  readonly onReceipt?: (receipt: JevAutomationReceipt) => void | Promise<void>;
}

export type JevAutomationStatus =
  | "completed"
  | "needs-agent"
  | "cancelled"
  | "budget-exhausted"
  | "failed";

export interface JevAutomationResult {
  readonly status: JevAutomationStatus;
  readonly reason: string;
  readonly observation: JevAutomationObservation | null;
  readonly assertions: readonly JevAutomationAssertionResult[];
  readonly receipts: readonly JevAutomationReceipt[];
  readonly decisionCalls: number;
  readonly executedSteps: number;
  readonly billedCostUsd: number | null;
}

const EMPTY_ACCOUNTING: JevAutomationAccounting = {
  inputTokens: null,
  outputTokens: null,
  costUsd: null,
};

function compareValue(
  actual: JevAutomationValue | undefined,
  operator: "equals" | "contains",
  expected: JevAutomationValue,
): boolean {
  if (operator === "equals") {
    if (Array.isArray(actual) && Array.isArray(expected))
      return (
        actual.length === expected.length &&
        actual.every((value, index) => value === expected[index])
      );
    return actual === expected;
  }
  if (typeof actual === "string" && typeof expected === "string") return actual.includes(expected);
  if (Array.isArray(actual) && typeof expected === "string") return actual.includes(expected);
  return false;
}

export function evaluateJevAutomationAssertions(
  observation: JevAutomationObservation,
  assertions: readonly JevAutomationAssertion[],
): readonly JevAutomationAssertionResult[] {
  return assertions.map((assertion) => {
    const incomplete = (observation.omissions?.length ?? 0) > 0;
    if (assertion.kind === "location") {
      const actual = observation[assertion.property];
      const matched = compareValue(actual, assertion.operator, assertion.expected);
      const indeterminate =
        actual === undefined ||
        (!matched && incomplete) ||
        (assertion.property === "visibleText" && assertion.operator === "equals" && incomplete);
      return {
        assertion,
        passed: matched && !indeterminate,
        verdict: indeterminate ? "indeterminate" : matched ? "passed" : "failed",
        ...(actual === undefined ? {} : { actual }),
        ...(indeterminate ? { reason: "The compact observation was incomplete." } : {}),
      };
    }
    const matches = observation.controls.filter((control) =>
      "targetId" in assertion && assertion.targetId !== undefined
        ? control.id === assertion.targetId
        : control.role === assertion.target.role && control.name === assertion.target.name,
    );
    if (assertion.kind === "control-count") {
      const passed =
        assertion.operator === "equals"
          ? matches.length === assertion.expected
          : assertion.operator === "at-least"
            ? matches.length >= assertion.expected
            : matches.length <= assertion.expected;
      const indeterminate = incomplete || assertion.target.scope !== undefined;
      return {
        assertion,
        passed: passed && !indeterminate,
        verdict: indeterminate ? "indeterminate" : passed ? "passed" : "failed",
        actual: matches.length,
        matchCount: matches.length,
        ...(indeterminate
          ? { reason: "A compact observation cannot prove scoped or complete match counts." }
          : {}),
      };
    }
    const control = matches.length === 1 ? matches[0] : undefined;
    const scoped = "target" in assertion && assertion.target.scope !== undefined;
    const ambiguousOrIncomplete = scoped || incomplete;
    if (assertion.kind === "control-exists") {
      const passed = matches.length === 1 && !ambiguousOrIncomplete;
      return {
        assertion,
        passed,
        verdict: ambiguousOrIncomplete ? "indeterminate" : passed ? "passed" : "failed",
        matchCount: matches.length,
        ...(ambiguousOrIncomplete
          ? { reason: "The compact observation cannot prove one complete scoped match." }
          : {}),
      };
    }
    const actual =
      assertion.property === "selectedLabel"
        ? (() => {
            const selected = control?.options?.filter((option) => option.selected) ?? [];
            return selected.length === 1 ? selected[0]!.label : undefined;
          })()
        : control?.[assertion.property];
    const matched = compareValue(actual, assertion.operator, assertion.expected);
    const indeterminate = ambiguousOrIncomplete || control === undefined;
    return {
      assertion,
      passed: matched && !indeterminate,
      verdict: indeterminate ? "indeterminate" : matched ? "passed" : "failed",
      ...(actual === undefined ? {} : { actual }),
      matchCount: matches.length,
      ...(indeterminate
        ? { reason: "The compact observation cannot establish one complete target match." }
        : {}),
    };
  });
}

function verificationProblem(
  assertions: readonly JevAutomationAssertion[],
  verification: JevAutomationVerificationResult,
): string | null {
  if (verification.results.length !== assertions.length)
    return "The verifier returned the wrong number of assertion results.";
  for (const [index, result] of verification.results.entries()) {
    if (JSON.stringify(result.assertion) !== JSON.stringify(assertions[index]))
      return "The verifier returned results for different assertions.";
    if (result.passed !== (result.verdict === "passed"))
      return "The verifier returned an inconsistent passed flag and verdict.";
    if (result.verdict === "passed" && result.coverage.status !== "complete")
      return "The verifier claimed success without complete coverage.";
    if (result.verdict === "passed" && result.document.status !== "current")
      return "The verifier claimed success against a document that was not current.";
  }
  return null;
}

function uniqueById<T extends { readonly id: string }>(values: readonly T[]): boolean {
  return new Set(values.map(({ id }) => id)).size === values.length;
}

function observationProblem(
  observation: JevAutomationObservation,
  inputs: readonly JevAutomationInput[],
): string | null {
  if (!observation.revision) return "The adapter returned an empty observation revision.";
  if (!uniqueById(observation.controls)) return "The adapter returned duplicate control ids.";
  if (!uniqueById(observation.candidates)) return "The adapter returned duplicate candidate ids.";
  if (!uniqueById(inputs)) return "The request supplied duplicate input ids.";
  const controls = new Set(observation.controls.map(({ id }) => id));
  const inputIds = new Set(inputs.map(({ id }) => id));
  for (const candidate of observation.candidates) {
    if (candidate.targetId !== undefined && !controls.has(candidate.targetId))
      return `Candidate ${candidate.id} references an unknown target.`;
    if (candidate.inputId !== undefined && !inputIds.has(candidate.inputId))
      return `Candidate ${candidate.id} references an unknown input.`;
  }
  return null;
}

function candidateProblem(
  candidate: JevAutomationCandidate,
  observation: JevAutomationObservation,
  input: JevAutomationInput | undefined,
): string | null {
  const control = candidate.targetId
    ? observation.controls.find(({ id }) => id === candidate.targetId)
    : undefined;
  if (control?.disabled) return "The selected target is disabled.";
  const requiredInputKinds: Partial<Record<JevAutomationOperation, JevAutomationInputKind>> = {
    "set-text": "text",
    "select-option": "option",
    scroll: "scroll",
    "press-key": "key",
  };
  const requiredInputKind = requiredInputKinds[candidate.operation];
  if (requiredInputKind !== undefined && input?.kind !== requiredInputKind)
    return `The selected operation requires a supplied ${requiredInputKind} input.`;
  if (candidate.operation === "navigate" && input?.kind !== "url" && input?.kind !== "navigation")
    return "The selected operation requires a supplied URL or logical navigation input.";
  if (
    (candidate.operation === "activate" ||
      candidate.operation === "set-checked" ||
      candidate.operation === "hover") &&
    input !== undefined
  )
    return `${candidate.operation} candidates cannot consume an input value.`;
  if (
    (candidate.operation === "activate" ||
      candidate.operation === "set-text" ||
      candidate.operation === "select-option" ||
      candidate.operation === "set-checked" ||
      candidate.operation === "hover") &&
    control === undefined
  )
    return "The selected operation requires a semantic target.";
  if (candidate.operation === "set-checked" && candidate.checked === undefined)
    return "The selected operation requires an explicit desired checked state.";
  if (candidate.operation !== "set-checked" && candidate.checked !== undefined)
    return "Only set-checked candidates can declare a checked state.";
  if (candidate.operation === "select-option" && input) {
    const option =
      input.kind === "option"
        ? control?.options?.find(({ value }) => value === input.value)
        : undefined;
    if (!option) return "The selected option is not available on the target.";
    if (option.disabled) return "The selected option is disabled.";
  }
  return null;
}

function meaningfulActionState(observation: JevAutomationObservation): string {
  const actionableTargetIds = new Set(
    observation.candidates.flatMap(({ targetId }) => (targetId === undefined ? [] : [targetId])),
  );
  const controls = observation.controls
    .filter(({ id }) => actionableTargetIds.has(id))
    .map(({ id, role, name, value, checked }) => [
      id,
      role,
      name ?? null,
      value ?? null,
      checked ?? null,
    ])
    .sort(([left], [right]) => String(left).localeCompare(String(right)));
  return JSON.stringify([observation.location ?? null, controls]);
}

function actionAttemptKey(
  observation: JevAutomationObservation,
  candidate: JevAutomationCandidate,
): string {
  const state =
    candidate.operation === "activate" || candidate.operation === "navigate"
      ? meaningfulActionState(observation)
      : observation.revision;
  return `${candidate.operation}\u0000${candidate.id}\u0000${state}`;
}

function terminalResult(input: {
  status: JevAutomationStatus;
  reason: string;
  observation: JevAutomationObservation | null;
  assertions: readonly JevAutomationAssertionResult[];
  receipts: readonly JevAutomationReceipt[];
  decisionCalls: number;
  executedSteps: number;
  billedCostUsd: number | null;
}): JevAutomationResult {
  return input;
}

/**
 * Runs only host-declared actions. Completion requires all supplied assertions to pass against a
 * fresh observation; a model cannot declare the task complete.
 */
export async function runJevAutomation(
  request: JevAutomationRequest,
  adapter: JevAutomationAdapter,
  decisionClient: JevAutomationDecisionClient,
): Promise<JevAutomationResult> {
  const inputs = request.inputs ?? [];
  const assertions = request.assertions ?? [];
  const maxSteps = request.limits?.maxSteps ?? 12;
  const maxDecisionCalls = request.limits?.maxDecisionCalls ?? 16;
  const maxCostUsd = request.limits?.maxCostUsd;
  const signal = request.signal ?? new AbortController().signal;
  const receipts: JevAutomationReceipt[] = [];
  let observation: JevAutomationObservation | null = null;
  let assertionResults: readonly JevAutomationAssertionResult[] = [];
  let decisionCalls = 0;
  let executedSteps = 0;
  let billedCostUsd: number | null = 0;
  let activeInputs = inputs;
  const unchangedAttempts = new Map<string, number>();

  const record = async (receipt: JevAutomationReceipt): Promise<boolean> => {
    receipts.push(receipt);
    try {
      await request.onReceipt?.(receipt);
      return true;
    } catch {
      return false;
    }
  };

  const finish = (status: JevAutomationStatus, reason: string) =>
    terminalResult({
      status,
      reason,
      observation,
      assertions: assertionResults,
      receipts,
      decisionCalls,
      executedSteps,
      billedCostUsd,
    });

  if (!Number.isSafeInteger(maxSteps) || maxSteps < 0)
    return finish("failed", "maxSteps must be a nonnegative safe integer.");
  if (!Number.isSafeInteger(maxDecisionCalls) || maxDecisionCalls < 0)
    return finish("failed", "maxDecisionCalls must be a nonnegative safe integer.");
  if (maxCostUsd !== undefined && (!Number.isFinite(maxCostUsd) || maxCostUsd < 0))
    return finish("failed", "maxCostUsd must be a nonnegative finite number.");

  while (true) {
    if (signal.aborted) return finish("cancelled", "Automation was cancelled.");
    try {
      observation = await adapter.observe({ signal });
    } catch {
      return finish(
        signal.aborted ? "cancelled" : "failed",
        signal.aborted ? "Automation was cancelled." : "The adapter could not observe the surface.",
      );
    }
    activeInputs = [...inputs, ...(observation.inputs ?? [])];
    const problem = observationProblem(observation, activeInputs);
    if (problem) return finish("failed", problem);
    if (assertions.length > 0) {
      if (!adapter.verify)
        return finish(
          "needs-agent",
          "The host adapter does not support independent targeted verification.",
        );
      let verification: JevAutomationVerificationResult;
      try {
        verification = await adapter.verify({
          assertions,
          ...(observation.document?.documentId === undefined
            ? {}
            : { expectedDocumentId: observation.document.documentId }),
          signal,
        });
      } catch {
        return finish(
          signal.aborted ? "cancelled" : "failed",
          signal.aborted
            ? "Automation was cancelled."
            : "The adapter could not independently verify the surface.",
        );
      }
      const problem = verificationProblem(assertions, verification);
      if (problem) return finish("failed", problem);
      assertionResults = verification.results;
      if (assertionResults.every(({ verdict }) => verdict === "passed"))
        return finish("completed", "All assertions passed independent targeted verification.");
    } else {
      assertionResults = [];
    }
    if (observation.candidates.length === 0)
      return finish("needs-agent", "The host adapter exposed no supported action candidates.");
    if (executedSteps >= maxSteps)
      return finish("budget-exhausted", "The execution step budget was exhausted.");
    if (decisionCalls >= maxDecisionCalls)
      return finish("budget-exhausted", "The decision-call budget was exhausted.");
    if (maxCostUsd !== undefined && billedCostUsd !== null && billedCostUsd >= maxCostUsd)
      return finish("budget-exhausted", "The billing budget was exhausted.");

    let decided: JevAutomationDecisionResult;
    try {
      decided = await decisionClient.decide({
        task: request.task,
        observation,
        inputs: activeInputs,
        unmetConditions: assertionResults.filter(({ verdict, passed }) =>
          verdict === undefined ? !passed : verdict !== "passed",
        ),
        priorReceipts: receipts,
        signal,
      });
    } catch {
      decided = {
        decision: { outcome: "unavailable", reason: "The decision client failed." },
        accounting: EMPTY_ACCOUNTING,
      };
    }
    decisionCalls += 1;
    billedCostUsd =
      decided.accounting.costUsd === null || billedCostUsd === null
        ? null
        : billedCostUsd + decided.accounting.costUsd;

    const baseReceipt = {
      iteration: decisionCalls,
      revision: observation.revision,
      decision: decided.decision,
      accounting: decided.accounting,
    } as const;
    if (signal.aborted) {
      await record({ ...baseReceipt, status: "rejected", detail: "Cancelled before execution." });
      return finish("cancelled", "Automation was cancelled.");
    }
    if (decided.decision.outcome === "unavailable") {
      await record({ ...baseReceipt, status: "unavailable", detail: decided.decision.reason });
      return finish("failed", `No valid Jev decision was available: ${decided.decision.reason}`);
    }
    if (decided.accounting.costUsd === null) {
      await record({
        ...baseReceipt,
        status: "rejected",
        detail: "Billing was unknown, so paid automation stopped before execution.",
      });
      return finish("budget-exhausted", "Billing was unknown; no action was executed.");
    }
    if (maxCostUsd !== undefined && billedCostUsd !== null && billedCostUsd > maxCostUsd) {
      await record({
        ...baseReceipt,
        status: "rejected",
        detail: "The paid decision exceeded the configured dollar budget.",
      });
      return finish("budget-exhausted", "The paid decision exceeded the billing budget.");
    }
    if (decided.decision.outcome === "needs-agent") {
      await record({ ...baseReceipt, status: "needs-agent" });
      return finish("needs-agent", `Jev requested an agent for ${decided.decision.reason}.`);
    }
    if (decided.decision.outcome === "done") {
      await record({
        ...baseReceipt,
        status: "needs-agent",
        detail: "Jev proposed completion, but the host assertions did not verify it.",
      });
      return finish(
        "needs-agent",
        assertions.length === 0
          ? "Jev proposed completion; independent verification is required because no assertions were supplied."
          : assertionResults.some(({ verdict }) => verdict === "indeterminate")
            ? "Jev proposed completion, but one or more host assertions were indeterminate."
            : "Jev proposed completion, but one or more host assertions remain unmet.",
      );
    }

    const selectedCandidateId = decided.decision.candidateId;
    const matches = observation.candidates.filter(
      (candidate) => candidate.id === selectedCandidateId,
    );
    if (matches.length !== 1) {
      await record({
        ...baseReceipt,
        status: "rejected",
        detail: "The selected action was not one unique host candidate.",
      });
      continue;
    }
    const candidate = matches[0]!;
    const attemptKey = actionAttemptKey(observation, candidate);
    const priorAttempts = unchangedAttempts.get(attemptKey) ?? 0;
    if (priorAttempts >= 1) {
      await record({
        ...baseReceipt,
        candidateId: candidate.id,
        status: "rejected",
        detail: "The same action was already executed without meaningful actionable progress.",
      });
      return finish(
        "needs-agent",
        "Repeated execution did not produce meaningful actionable progress.",
      );
    }
    const suppliedInput = candidate.inputId
      ? activeInputs.find(({ id }) => id === candidate.inputId)
      : undefined;
    const rejection = candidateProblem(candidate, observation, suppliedInput);
    if (rejection) {
      await record({
        ...baseReceipt,
        candidateId: candidate.id,
        status: "rejected",
        detail: rejection,
      });
      continue;
    }
    const action: JevAutomationAction = {
      candidateId: candidate.id,
      operation: candidate.operation,
      ...(candidate.targetId === undefined ? {} : { targetId: candidate.targetId }),
      ...(candidate.inputId === undefined ? {} : { inputId: candidate.inputId }),
      ...(suppliedInput === undefined || suppliedInput.kind === "navigation"
        ? {}
        : { value: suppliedInput.value }),
      ...(suppliedInput?.kind === "navigation" ? { navigationTarget: suppliedInput.target } : {}),
      ...(candidate.checked === undefined ? {} : { checked: candidate.checked }),
    };
    if (
      !(await record({
        ...baseReceipt,
        candidateId: candidate.id,
        status: "proposed",
      }))
    )
      return finish("failed", "The action proposal receipt could not be persisted.");
    if (signal.aborted) {
      await record({
        ...baseReceipt,
        candidateId: candidate.id,
        status: "rejected",
        detail: "Cancelled after proposal persistence and before execution.",
      });
      return finish("cancelled", "Automation was cancelled before execution.");
    }
    let execution: JevAutomationExecutionResult;
    let executionThrew = false;
    try {
      execution = await adapter.execute({
        revision: observation.revision,
        action,
        signal,
      });
    } catch {
      executionThrew = true;
      execution = signal.aborted
        ? { status: "rejected", detail: "Cancelled during execution." }
        : {
            status: "rejected",
            detail: "The adapter threw after execution began; the mutation outcome is unknown.",
          };
    }
    if (
      !(await record({
        ...baseReceipt,
        candidateId: candidate.id,
        status: execution.status,
        ...(execution.detail === undefined ? {} : { detail: execution.detail }),
      }))
    )
      return finish("failed", "The execution receipt could not be persisted.");
    if (signal.aborted) return finish("cancelled", "Automation was cancelled.");
    if (executionThrew)
      return finish(
        "needs-agent",
        "Execution failed with an unknown mutation outcome; independent verification is required.",
      );
    if (execution.status === "executed") {
      executedSteps += 1;
      unchangedAttempts.set(attemptKey, priorAttempts + 1);
    }
  }
}
